### ISSUE TITLE
Warning: `value` prop on `input` should not be null.

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#19]
On page /new I get the following console warning on dev server:

```
client.js:1 Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    at input
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:23398)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:23398)
    at SingleLineInput (webpack-internal:///./components/ContactForm/SingleLineInput/SingleLineInput.js:13:11)
    at fieldset
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:23398)
    at form
    at ContactForm (webpack-internal:///./components/ContactForm/ContactForm.js:32:11)
    at CreateNewContactPage (webpack-internal:///./pages/new/index.js:17:11)
    at main
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:23398)
    at Layout (webpack-internal:///./components/Layout/Layout.js:13:11)
    at App (webpack-internal:///./pages/_app.js:23:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:306:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:858:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:92:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:196:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:374:11)
console.error @ client.js:1
window.console.error @ next-dev.js:27
overrideMethod @ console.js:213
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
validateProperties$1 @ react-dom.development.js:3644
validatePropertiesInDevelopment @ react-dom.development.js:9540
setInitialProperties @ react-dom.development.js:9830
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 1 more frame
```

**Comment by josch87** [comment]
If field dateOfBirth is undefined it was rendered as null. Changed to empty string.
